title: Rui Jiang # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/rui21/">LinkedIn</a> 
  <br>
  Hi! My name is Rui['rej̯].
  <br><br>
  I started by studying how nature sustains life — through Environmental Science and Applied Geoscience.<br>
  At the Water Center at UPenn, my perspective expanded from the natural to the built environment, where I began exploring how cities can sustain life too.<br>
  It wasn’t a shift in direction — it was an expansion of perspective, from ecosystems to urban systems, from what nature teaches us to what cities can become.
  <br><br>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
